# Generated by Django 2.2 on 2019-05-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='地点')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('telephone', models.CharField(max_length=50, verbose_name='电话')),
                ('email', models.CharField(max_length=50, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name': '联系',
                'verbose_name_plural': '联系方式',
            },
        ),
    ]
