# Generated by Django 2.2 on 2019-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=50, verbose_name='项目名称')),
                ('detail', models.TextField(verbose_name='项目简介')),
            ],
            options={
                'verbose_name': '案例',
                'verbose_name_plural': '项目案例',
            },
        ),
    ]
