# Generated by Django 2.2 on 2019-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190526_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '联系', 'verbose_name_plural': '联系方式'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '关于', 'verbose_name_plural': '关于我们'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(max_length=50, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
