# Generated by Django 2.2 on 2019-05-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20190527_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
