# Generated by Django 2.2 on 2019-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '首页', 'verbose_name_plural': '首页信息'},
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
