# Generated by Django 2.2 on 2019-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('function', models.TextField()),
                ('customer', models.CharField(max_length=15)),
                ('case', models.TextField()),
            ],
        ),
    ]
